# Numpy - Numerical Python



## Homework

### Task 1

In [ ]:
import numpy as np

my_list = [12.23, 13.32, 100, 36.32]

print(np.array(my_list))


[ 12.23  13.32 100.    36.32]


### Task 2

In [14]:
import numpy as np

num = range(2,11)

print(np.array(num).reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Task 3

In [ ]:
import numpy as np

nulls = np.zeros(10)

nulls[7] = 11

print(nulls)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.])

### Task 4

In [26]:
import numpy as np 

arr = np.arange(12,39)

print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


### Task 5

In [28]:
import numpy as np

arr_int = np.arange(1,5)

arr_float = arr_int.astype(float)

print(arr_float)

[1. 2. 3. 4.]


### Task 6


In [ ]:
import numpy as np

fahrenheit_values = np.array([0, 12, 45.21, 34, 99.91, 32])
celsius_values = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])

# Conversion formulas
# Celsius to Fahrenheit: F = C * 9/5 + 32
# Fahrenheit to Celsius: C = (F - 32) * 5/9

# Convert Celsius to Fahrenheit
converted_fahrenheit = np.round(celsius_values * 9/5 + 32, 2)

# Convert Fahrenheit to Celsius
converted_celsius = np.round((fahrenheit_values - 32) * 5/9, 2)

print("Values in Fahrenheit degrees:", fahrenheit_values)
print("Values in Centigrade degrees:", converted_celsius)

print("Values in Centigrade degrees:", celsius_values)
print("Values in Fahrenheit degrees:", converted_fahrenheit)

Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-0.   12.   45.21 34.   99.91 32.  ]


### Task 7

In [6]:
import numpy as np 

arr_tsk7 = np.array( [10, 20, 30])

appended_arr = np.append(arr_tsk7, [40, 50, 60, 70, 80, 90])

print(appended_arr)

[10 20 30 40 50 60 70 80 90]


### Task 8

In [ ]:
import numpy as np

rand_arr = np.random.randint(1, 100, 10) 

mean = np.mean(rand_arr)
median = np.median(rand_arr)
standart_deviation = np.std(rand_arr)


print("Original array:", rand_arr)
print("Mean of the array:", mean)
print("Median od the array:", median)
print("Standart deviation of the array:", standart_deviation)

Original array: [26  4  2 99 89 77  4 48  4 66]
Mean of the array: 41.9
Median od the array: 37.0
Standart deviation of the array: 36.71906861563893


### Task 9

In [100]:
import numpy as np

arr_tsk9 = np.random.randint(1, 250, size=(10,10))
minimum = np.min(arr_tsk9)
maximum = np.max(arr_tsk9)

print("Original array:", arr_tsk9)
print("Minimum value of the array:", minimum)
print("Maximum value of the array:", maximum)

Original array: [[ 22  85 118   3  53   9 190 119 190  57]
 [117  84 131 175  75 216  52 117  68  43]
 [173 156 178   9 236 126 192  87  89 223]
 [ 19 116 175 189 233 233 222 231  21 232]
 [204  16 168 163 144   3 182 173 147  13]
 [ 88 212 179 110 105 184 144 178   7 183]
 [231 141 101 141 202 107 203 180 208 151]
 [ 12  39  17 146  96  89 205  58  54 109]
 [169 193  92  99 196 200 195 139 167  59]
 [ 52  58 216  17 121 169  24  40  90 233]]
Minimum value of the array: 3
Maximum value of the array: 236


### Task 10

In [ ]:
import numpy as np

arr_tsk10 = np.random.randn(3,3,3)

print(arr_tsk10)

array([[[ 0.41152004, -0.6024211 ,  1.26962382],
        [-1.3540478 ,  0.80368322,  0.42503386],
        [ 0.22659217,  0.10806699, -0.46889776]],

       [[ 0.82247643, -0.55193151,  0.06704991],
        [ 0.14894327,  0.25984381,  0.2799092 ],
        [ 1.15886875,  2.34605362, -0.21210332]],

       [[ 0.50139963, -1.177569  , -1.05878696],
        [-0.29843152,  0.94721305, -2.01989969],
        [ 0.19265451,  0.82823603, -1.34659645]]])